# Generated by Django 2.1.5 on 2020-01-22 02:05

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_image'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='userprofile',
            managers=[
                ('chicago', django.db.models.manager.Manager()),
            ],
        ),
    ]
