# Generated by Django 2.1.5 on 2020-01-23 00:36

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200122_0205'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='userprofile',
            managers=[
                ('salamie', django.db.models.manager.Manager()),
            ],
        ),
    ]
